### ISSUE TITLE
docs don't match the implementation at all

### ISSUE THREAD

**Issue by mmerickel** [servo/rust-png#80]
The docs at http://doc.servo.org/png/ are totally incorrect compared to the current API. Just found this library and played around with it and it works great for loading/writing png files but the incorrect docs were a bummer.

**Comment by jdm** [comment]
I'm surprised there have been that many meaningful changes to it since we stopped using it in Servo (and therefore stopped pushing the updated documentation automatically).

**Comment by Ms2ger** [comment]
http://doc.servo.org/png/ is for https://github.com/PistonDevelopers/image-png , not this repo. We should probably mark this repo as unmaintained.
